### ISSUE TITLE
Buat Database dan Logic Untuk Sistem Discount per Subkategori

### ISSUE THREAD

**Issue by NRayaa** [NRayaa/inbound-sample#12]
Nantinya ketika subkategori dipilih, akan otomatis harga asli terpotong dengan discount yang sesuai dengan sub kategori
1. Input discount sesuai yang diinginkan
2. klik update, nanti di sistem database akan memperbarui discountnya

![image](https://github.com/NRayaa/inbound-sample/assets/116838581/b81ce100-3587-43b1-a969-28d8fc5d29e0)

**Comment by laluisari** [comment]
database untuk diskon dan harga di atas 100k , dibawah 100k dan diskon






![Image](https://github.com/NRayaa/inbound-sample/assets/82717953/da765d63-26ab-4d9a-be9f-815902ca0b50)







api untuk crud diskon 



![Image](https://github.com/NRayaa/inbound-sample/assets/82717953/57627c57-94f9-4688-b08e-343de7e1c434)
