### ISSUE TITLE
Buat Design Databse untuk Report

### ISSUE THREAD

**Issue by NRayaa** [NRayaa/inbound-sample#16]
Report sendiri akan menampung data jumlah barang data awal, jumlah barang data setelan di check, jumlah barang yang lolos QC, jumlah barang yg tidak lolos QC, jumlah barang yang subkategori 1 2 3 dst, jumlah barang tag warna 1 2 dst, dan jumlah barang yg tak tercheck/hilang.

Report DB
ID Dokumen
Jumlah data awal
Jumlah data akhir (ada)
Jumlah data akhir (tidak ada) -> jumlah data awal - jmlah data akhir
Jumlah data barang subkategori 1
Jumlah data barang subkategori 2
Jumlah data barang subkategori 3
Jumlah data barang subkategori dst
Jumlah data barang tag warna 1
Jumlah data barang tag warna 2
Jumlah data barang lolos QC
Jumlah data barang tidak lolos QC/rusak
Jumlah data barang tidak lolos QC/Discrepancy
Jumlah data barang tidak lolos QC/Abnormal
Jumlah data barang tidak lolos QC/Tidak ada Keterangan (TK)

![Image](https://github.com/NRayaa/inbound-sample/assets/116838581/ef19144e-38d6-4310-b449-a7a0c74fbe48)

**Comment by laluisari** [comment]
berikut nanti tampilan dari laporan

![Image](https://github.com/NRayaa/inbound-sample/assets/82717953/f35581fc-a64f-4d6b-85c1-2ca6c3d1a1d8)

setelah itu, mnugkin akan ada tombol inputin ke db dan generates ke file excel
