### ISSUE TITLE
Buat Design Database -> sama screenshot nya ya - (Logic)

### ISSUE THREAD

**Issue by NRayaa** [NRayaa/inbound-sample#2]
Database system untuk proses inbound yang bisa menampung : 
1. Uplaod Excel
2. Save header yang mau dipakai
3. Save Produk untuk check
4. Pencocokan list dengan produk barcode(scan)
5. report

**Comment by laluisari** [comment]
screenshoot schema database versi GUI dari drawsql
tabel untuk simpan data generates dan merged hasil generates

![Image](https://github.com/NRayaa/inbound-sample/assets/82717953/dc96d47a-24e2-46e9-a763-2d8839eeb01e)
