### ISSUE TITLE
Buat Form Uplaod Excel dari Ekspedisi - (Logic)

### ISSUE THREAD

**Issue by NRayaa** [NRayaa/inbound-sample#3]
Form Upload Excel (untuk gambaran lihat di gambar flow):
1. Bisa upload banyak file sekali upload
2. Setelah input akan masuk ke dalam database (untuk pendataan)
3.  setelah submit akan direct ke halaman selanjutnya (issue selanjutnya -> pilih header)

**Comment by laluisari** [comment]
1. Bisa upload banyak file sekali upload

lebih dari 1 file 


![Image](https://github.com/NRayaa/inbound-sample/assets/82717953/f03e0b8b-3e5d-4582-8f2b-c46d47e24742)


![Image](https://github.com/NRayaa/inbound-sample/assets/82717953/a0cae6d2-95b4-48cc-a702-3cb640e691bd)


2. Setelah input akan masuk ke dalam database (untuk pendataan)
 
masukkan data dari hasil generate dari setiap header file ke database ke table

![Image](https://github.com/NRayaa/inbound-sample/assets/82717953/23ce4d29-b3d3-4234-b4dc-b301ceb97839)

3. setelah submit akan direct ke halaman selanjutnya (issue selanjutnya -> pilih header)


![Image](https://github.com/NRayaa/inbound-sample/assets/82717953/bebade7d-24b8-40b9-8ec0-57d8aef0745e)
