### ISSUE TITLE
Buat Form Untuk Pilih Header - (Logic)

### ISSUE THREAD

**Issue by NRayaa** [NRayaa/inbound-sample#4]
Form Pilih Header (untuk gambar ada di flow) :
1. Setelah input file excel ekspedisi (issue sebelumnya -> form upload excel ekspedisi) redirect untuk issue ini
2. Menampilkan semua header dari excel yang sudah di upload (berbentuk list sesuai file) -> lebih jelasnya lihat di flow
3. Di setiap header yg muncul ada chekclist untuk memilih data dengan header apa aja yang akan dipakai
4. Nnatinya data dengan header yang dipilih akan di merge, (dari banyak list didalam file excel -> jadi satu list)
5. Jika sudah dipilih akan redirect ke halaman selanjutnya (issue selanjutnya -> membut tampilan list merge)

**Comment by laluisari** [comment]
done, sama dengan issue ke 5
