### ISSUE TITLE
Buat View Table untuk Menampilkan Hasil Data dari Berbagai Excel (Merge) - (Logic)

### ISSUE THREAD

**Issue by NRayaa** [NRayaa/inbound-sample#5]
Membuat tampilan tabel untuk menampilkan data dari berbagai excel sesuai dengan header-header yang telah dipilih (issue sebelumnya -> form memilih header)

1. Mengambil data sesuai dengan header yang dipilih -> issue sebelumnya
2. Menggabungkan data-data dari file-file yang sudah di upload sebelumnya
3. Menampilkan data-data yang sudah digabungkan (merge)
4. Buat button untuk redirect ke halaman selanjutnya -> (issue selanjutnya -> membuat form check barcode)

note : ketika button di klik, setiap check barcode akan menyesuaikan dengan data yang ada di dalam list data excel yang sudah di merge tadi.

**Comment by laluisari** [comment]
1. mengambil data sesuai dengan header yang di pilih  dari generates file excel yang di input


![Image](https://github.com/NRayaa/inbound-sample/assets/82717953/83a9f1d2-c46b-40f9-b7fd-98c7d4eae3a9)

2. menggabungkan data yang di pilih ke template headers

![Image](https://github.com/NRayaa/inbound-sample/assets/82717953/41c8e19f-e473-4555-bb6a-908f4ca75dc4)

3. menampilkan data yang sudah digabungkan 



![Image](https://github.com/NRayaa/inbound-sample/assets/82717953/84994c94-382a-46b5-a7b7-9ebf2dd96c7c)
