### ISSUE TITLE
Buat Form untuk Check Barcode - (Logic)

### ISSUE THREAD

**Issue by NRayaa** [NRayaa/inbound-sample#6]
Membuat form untuk check barcode. Nantinya setelah dari halaman sebelumnya (issue membuat halaman menampilkan data excel) alur nya adalah, setiap produk akan di cek satu persatu dengan menyesuaikan data dengan yang sudah di merge. data akan dibaca dulu, apakah harganya >100k atau <100k. (gambaran ada di kolom assets->(IF ELSE CheckBarcode)
1. =>100k sesuai dengan gambar di flow sebelah kanan
2. <100k sesuai dengan gambar di flow sebelah kiri

Didalam form (>100k) ini akan menyimpan+update data yang ada didalam list
1. Menyimpan Subkategori
2. Menyimpan Price yang telah di discount
3. Menyimpan barang Lolos QC dan tidak Lolos QC (QCD)
4. Discount sesuai dengan data yang sudah ada (sesuai subkategori) lihat kolom assets (subkategori discount)

Didalam form (<100k) ini akan menyimpan+update data yang ada didalam list
1. menyimpan subkategori
2. Menyimpan Tag Warna (biasanya ada 2 tag warna, ex: merah dan biru-> merah<50k & biru<100k
3. Menyimpan barang Lolos QC dan tidak Lolos QC
4. Fitur Discount dipakai hanya untuk yang >100k

**Comment by laluisari** [comment]
done

input data untuk harga hasil check barcode(no_resi) di atas 100k


![Image](https://github.com/NRayaa/inbound-sample/assets/82717953/40feea35-fd0f-47a3-9133-ccf4533b6098)

berikut data yang tersimpan di database

![Image](https://github.com/NRayaa/inbound-sample/assets/82717953/b87084ef-ccc0-4cee-a63f-bfb22fd1cb88)


input data untuk harga hasil check barcode(no_resi) di bawah 100k


![Image](https://github.com/NRayaa/inbound-sample/assets/82717953/ed4f4574-fb82-4a40-a5ec-322fec137194)


dan ini adalah hasil data inputan yang masuk ke daabase 


![Image](https://github.com/NRayaa/inbound-sample/assets/82717953/5d371722-5e9d-4af0-8554-1ba229f69cad)
